# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0ba1a344aee4087ee56b570a69c7fb533b2c8a47c4739cff4b5405ff7ac741b5d54c99c13e3bb2dcab4f1b2c227c4c19bbdc6a5f1850aa4778ab357a76ebfc2a

test:
  secret_key_base: c7a88f8a17b019300d8c6557be706ca339e60d7e1c2c53cf353e44fb6ad5568f66e61e5c4772879f7393d5a32b14f8efea27c4706d6d93ce85114ac296e9640b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
